#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace MobilityScm.Modelo.Entidades
{
	[Table("SWIFT_TXNS")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class SwiftTxn
	{
		private int _txnid;
		[Column("TXN_ID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_txnid")]
		public virtual int TxnId
		{
			get
			{
				return this._txnid;
			}
			set
			{
				this._txnid = value;
			}
		}

		private int? _manifestsource;
		[Column("MANIFEST_SOURCE", OpenAccessType = OpenAccessType.Int32, IsNullable = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_manifestsource")]
		public virtual int? ManifestSource
		{
			get
			{
				return this._manifestsource;
			}
			set
			{
				this._manifestsource = value;
			}
		}

		private string _sapreference;
		[Column("SAP_REFERENCE", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 50, Scale = 0, SqlType = "varchar")]
		[Storage("_sapreference")]
		public virtual string SapReference
		{
			get
			{
				return this._sapreference;
			}
			set
			{
				this._sapreference = value;
			}
		}

		private int? _tasksourceid;
		[Column("TASK_SOURCE_ID", OpenAccessType = OpenAccessType.Int32, IsNullable = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_tasksourceid")]
		public virtual int? TaskSourceId
		{
			get
			{
				return this._tasksourceid;
			}
			set
			{
				this._tasksourceid = value;
			}
		}

		private string _txntype;
		[Column("TXN_TYPE", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 25, Scale = 0, SqlType = "varchar")]
		[Storage("_txntype")]
		public virtual string TxnType
		{
			get
			{
				return this._txntype;
			}
			set
			{
				this._txntype = value;
			}
		}

		private string _txndescription;
		[Column("TXN_DESCRIPTION", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 50, Scale = 0, SqlType = "varchar")]
		[Storage("_txndescription")]
		public virtual string TxnDescription
		{
			get
			{
				return this._txndescription;
			}
			set
			{
				this._txndescription = value;
			}
		}

		private string _txncategory;
		[Column("TXN_CATEGORY", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 25, Scale = 0, SqlType = "varchar")]
		[Storage("_txncategory")]
		public virtual string TxnCategory
		{
			get
			{
				return this._txncategory;
			}
			set
			{
				this._txncategory = value;
			}
		}

		private DateTime? _txncreatedstamp;
		[Column("TXN_CREATED_STAMP", OpenAccessType = OpenAccessType.DateTime, IsNullable = true, Length = 0, Scale = 0, SqlType = "datetime")]
		[Storage("_txncreatedstamp")]
		public virtual DateTime? TxnCreatedStamp
		{
			get
			{
				return this._txncreatedstamp;
			}
			set
			{
				this._txncreatedstamp = value;
			}
		}

		private string _txnoperatorid;
		[Column("TXN_OPERATOR_ID", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 25, Scale = 0, SqlType = "varchar")]
		[Storage("_txnoperatorid")]
		public virtual string TxnOperatorId
		{
			get
			{
				return this._txnoperatorid;
			}
			set
			{
				this._txnoperatorid = value;
			}
		}

		private string _txnoperatorname;
		[Column("TXN_OPERATOR_NAME", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 250, Scale = 0, SqlType = "varchar")]
		[Storage("_txnoperatorname")]
		public virtual string TxnOperatorName
		{
			get
			{
				return this._txnoperatorname;
			}
			set
			{
				this._txnoperatorname = value;
			}
		}

		private string _txncodesku;
		[Column("TXN_CODE_SKU", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 50, Scale = 0, SqlType = "varchar")]
		[Storage("_txncodesku")]
		public virtual string TxnCodeSku
		{
			get
			{
				return this._txncodesku;
			}
			set
			{
				this._txncodesku = value;
			}
		}

		private string _txndescriptionsku;
		[Column("TXN_DESCRIPTION_SKU", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 250, Scale = 0, SqlType = "varchar")]
		[Storage("_txndescriptionsku")]
		public virtual string TxnDescriptionSku
		{
			get
			{
				return this._txndescriptionsku;
			}
			set
			{
				this._txndescriptionsku = value;
			}
		}

		private decimal? _txnqty;
		[Column("TXN_QTY", OpenAccessType = OpenAccessType.Numeric, IsNullable = true, Length = 18, Scale = 2, SqlType = "numeric")]
		[Storage("_txnqty")]
		public virtual decimal? TxnQty
		{
			get
			{
				return this._txnqty;
			}
			set
			{
				this._txnqty = value;
			}
		}

		private int? _headerreference;
		[Column("HEADER_REFERENCE", OpenAccessType = OpenAccessType.Int32, IsNullable = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_headerreference")]
		public virtual int? HeaderReference
		{
			get
			{
				return this._headerreference;
			}
			set
			{
				this._headerreference = value;
			}
		}

		private int? _txnattemptedwitherror;
		[Column("TXN_ATTEMPTED_WITH_ERROR", OpenAccessType = OpenAccessType.Int32, IsNullable = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_txnattemptedwitherror")]
		public virtual int? TxnAttemptedWithError
		{
			get
			{
				return this._txnattemptedwitherror;
			}
			set
			{
				this._txnattemptedwitherror = value;
			}
		}

		private int? _txnispostederp;
		[Column("TXN_IS_POSTED_ERP", OpenAccessType = OpenAccessType.Int32, IsNullable = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_txnispostederp")]
		public virtual int? TxnIsPostedErp
		{
			get
			{
				return this._txnispostederp;
			}
			set
			{
				this._txnispostederp = value;
			}
		}

		private DateTime? _txnpostederp;
		[Column("TXN_POSTED_ERP", OpenAccessType = OpenAccessType.DateTime, IsNullable = true, Length = 0, Scale = 0, SqlType = "datetime")]
		[Storage("_txnpostederp")]
		public virtual DateTime? TxnPostedErp
		{
			get
			{
				return this._txnpostederp;
			}
			set
			{
				this._txnpostederp = value;
			}
		}

		private string _txnpostedresponse;
		[Column("TXN_POSTED_RESPONSE", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 150, Scale = 0, SqlType = "varchar")]
		[Storage("_txnpostedresponse")]
		public virtual string TxnPostedResponse
		{
			get
			{
				return this._txnpostedresponse;
			}
			set
			{
				this._txnpostedresponse = value;
			}
		}

		private string _txnsignature;
		[Column("TXN_SIGNATURE", OpenAccessType = OpenAccessType.StringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "varchar(max)")]
		[Storage("_txnsignature")]
		public virtual string TxnSignature
		{
			get
			{
				return this._txnsignature;
			}
			set
			{
				this._txnsignature = value;
			}
		}

		private int? _txntasksource;
		[Column("TXN_TASK_SOURCE", OpenAccessType = OpenAccessType.Int32, IsNullable = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_txntasksource")]
		public virtual int? TxnTaskSource
		{
			get
			{
				return this._txntasksource;
			}
			set
			{
				this._txntasksource = value;
			}
		}

		private string _txnimage1;
		[Column("TXN_IMAGE_1", OpenAccessType = OpenAccessType.StringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "varchar(max)")]
		[Storage("_txnimage1")]
		public virtual string TxnImage1
		{
			get
			{
				return this._txnimage1;
			}
			set
			{
				this._txnimage1 = value;
			}
		}

		private string _txnbatch;
		[Column("TXN_BATCH", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 50, Scale = 0, SqlType = "varchar")]
		[Storage("_txnbatch")]
		public virtual string TxnBatch
		{
			get
			{
				return this._txnbatch;
			}
			set
			{
				this._txnbatch = value;
			}
		}

		private string _txnserie;
		[Column("TXN_SERIE", OpenAccessType = OpenAccessType.StringVariableLength, IsNullable = true, Length = 75, Scale = 0, SqlType = "varchar")]
		[Storage("_txnserie")]
		public virtual string TxnSerie
		{
			get
			{
				return this._txnserie;
			}
			set
			{
				this._txnserie = value;
			}
		}

	}
}
#pragma warning restore 1591